name: Hello Infra Runner

on:
  push:
     branches: [ main,dev ]

jobs:
   hello:
       runs-on: [ infra ]
       steps:
          - name: Say Hello
            run: echo "Hello I am running  this job on self hosted runner"
          - name: Print Terraform Version
            run: |
                if [[ "$GITHUB_REF" == "/ref/heads/main" ]]; then
                      echo "Running code from main branch"
                else
                    echo "Running code from dev branch"
                fi    
