name: Hello Infra Runner

on: 
  push

jobs:
   hello:
       runs-on: [ infra ]
       steps:
          - name: Say Hello
            run: echo "Hello I am running  this job on self hosted runner"
          - name: Print Terraform Version
            run: |
                if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
                      echo "Running terraform for branch $GITHUB_REF_NAME"
                      terraform init
                      terraform plan 
                      terrafrom apply -f $GITHUB_REF_NAME.tfvars --auto-approve
                elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
                    echo "Running terraform for branch $GITHUB_REF_NAME"
                    terraform init
                    terraform plan 
                    terraform apply -f $GITHUB_REF_NAME.tfvars
                else
                  echo "I am allowed to run the flow in dev or main branch"
                fi    
