name: Hello Infra Runner

on: 
  push

jobs:
   build:
     uses: ./.github/workflows/template.yaml
   test:
     runs-on: [infra]
     needs: [build]
     steps:
       - name: Running Test Job
         run: echo "Run test job"

   deploy:
     runs-on: [infra]
     needs: [build, test]
     steps:
      - name: Running Deploy Job
        run: echo "Run Deploy Job"
     

